// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: customers.sql

package db

import (
	"context"
)

const getCustomerById = `-- name: GetCustomerById :one
SELECT id, customer_name, created_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerById(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerById, id)
	var i Customer
	err := row.Scan(&i.ID, &i.CustomerName, &i.CreatedAt)
	return i, err
}
