// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID           string
	CustomerName string
	CreatedAt    pgtype.Timestamptz
}

type Product struct {
	ID          string
	ProductName string
	Price       pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
}

type Transaction struct {
	ID         string
	CustomerID string
	ProductID  string
	Quantity   int32
	TotalPrice pgtype.Numeric
	CreatedAt  pgtype.Timestamptz
}
