// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetCustomerById(ctx context.Context, id string) (Customer, error)
	GetProductById(ctx context.Context, id string) (Product, error)
	GetTransactionById(ctx context.Context, id string) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
