// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Analytic struct {
	ID           string
	TopCustomers int32
	TotalSales   pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
}

type Transaction struct {
	ID           string
	CustomerID   string
	CustomerName string
	ProductID    string
	ProductName  string
	Quantity     int32
	TotalPrice   pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
}
